image: maven:3.9.6-eclipse-temurin-17

pipelines:
  pull-requests:
    "**":
      - step:
          name: Build & Test
          script:
            - mvn test

  branches:
    main:
      - step:
          name: Deploy
          script:
            - kubectl apply -f k8s/
